Battlefield/Dashboards/BloatedInternalDash/config/routes.rb
Rails.application.routes.draw do

  resources :systems

  namespace :api do
    resources :projects do
      resources :issues #, only: [:create, :update, :destroy]
    end

    resources :servers do
      resources :services
      resources :connections
      resources :pids
    end

  end

  get 'progress/main'

  get 'progress/detail'

  get 'progress/graphs'

  get 'progress/statistics'

  get 'files/index'

  get 'files/download'

  get 'files/upload'

  get 'public/index'

  get 'public/show'

   resources :projects do
     resources :issuelists
     resources :tasklists
   end
  resources :notifications
  resources :networks
  resources :network_boxes
  resources :memberships
  resources :logfiles
  resources :logentries
  resources :hardwares
  resources :githubs
  resources :gists
  resources :groups
  resources :domainnames
  resources :networks
  resources :clusters
  resources :services
  resources :infrastructures
  resources :organizations
  resources :labels
  resources :milestones
  resources :todos

  resources :tasklists do
    resources :tasks
  end
  resources :issuelists do
    resources :issues
  end

  resources :ips
  get 'home/slice'

  resources :ips
  resources :reputations
  resources :ips
  resources :organizations
  resources :nodes
  resources :servers
  get 'dashboard/index'

  get 'dashboard/controls'

  get 'dashboard/analysis'

  devise_for :users
  get 'clusterjobs/new'

  get 'clusterjobs/index'

  get 'main/index'

  root 'main#index'

  resources :systems
  get 'progress/main'

  get 'progress/detail'

  get 'progress/graphs'

  get 'progress/statistics'

  get 'files/index'

  get 'files/download'

  get 'files/upload'

  get 'public/index'

  get 'public/show'

  resources :notifications
  resources :networks
  resources :network_boxes
  resources :memberships
  resources :logfiles
  resources :logentries
  resources :hardwares
  resources :githubs
  resources :gists
  resources :groups
  resources :domainnames
  resources :networks
  resources :clusters
  resources :services
  resources :infrastructures
  resources :organizations
  resources :labels
  resources :milestones
  resources :todos
  resources :tasks
  resources :tasklists
  resources :issues
  resources :issuelists
  resources :projects
  resources :ips
  get 'home/slice'

end

Battlefield/Dashboards/BloatedInternalDash/app/models/ip.rb
class Ip < ActiveRecord::Base
  has_many :domainnames
  # include Mongoid::Document
  # field :address, type: String
  # field :hostname, type: Integer
  # field :dns, type: String
  # field :isp, type: String
  # field :netblock, type: String
  # field :subnet, type: String
  # field :reputation, type: Integer
  # embedded_in :network
  # embedded_in :dns
  # embedded_in :organization
end

Battlefield/Dashboards/BloatedInternalDash/app/models/supermodels/org/ip.rb
module Org
	class Ip < ActiveRecord::Base
		belongs_to :organization
		belongs_to :infrastructure
		belongs_to :server
		has_many :webpages
		belongs_to :webserver
		has_and_belongs_to_many :domains
	end
end

Battlefield/Dashboards/BloatedInternalDash/app/controllers/ips_controller.rb
class IpsController < ApplicationController
  before_action :set_ip, only: [:show, :edit, :update, :destroy]

  # GET /ips
  # GET /ips.json
  def index
    @ips = Ip.all
  end

  # GET /ips/1
  # GET /ips/1.json
  def show
  end

  # GET /ips/new
  def new
    @ip = Ip.new
  end

  # GET /ips/1/edit
  def edit
  end

  # POST /ips
  # POST /ips.json
  def create
    @ip = Ip.new(ip_params)

    respond_to do |format|
      if @ip.save
        format.html { redirect_to @ip, notice: 'Ip was successfully created.' }
        format.json { render :show, status: :created, location: @ip }
      else
        format.html { render :new }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ips/1
  # PATCH/PUT /ips/1.json
  def update
    respond_to do |format|
      if @ip.update(ip_params)
        format.html { redirect_to @ip, notice: 'Ip was successfully updated.' }
        format.json { render :show, status: :ok, location: @ip }
      else
        format.html { render :edit }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ips/1
  # DELETE /ips/1.json
  def destroy
    @ip.destroy
    respond_to do |format|
      format.html { redirect_to ips_url, notice: 'Ip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ip
      @ip = Ip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ip_params
      params.require(:ip).permit(:address, :hostname, :dns, :isp, :netblock, :subnet, :network_id, :reputation, :dns_id, :organization_id)
    end
end

Battlefield/Dashboards/BloatedInternalDash/app/helpers/ips_helper.rb
module IpsHelper
end

Battlefield/Dashboards/BloatedInternalDash/app/views/ips/_form.html.erb
<%= form_for(@ip) do |f| %>
  <% if @ip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ip.errors.count, "error") %> prohibited this ip from being saved:</h2>

      <ul>
      <% @ip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :hostname %><br>
    <%= f.number_field :hostname %>
  </div>
  <div class="field">
    <%= f.label :dns %><br>
    <%= f.text_field :dns %>
  </div>
  <div class="field">
    <%= f.label :isp %><br>
    <%= f.text_field :isp %>
  </div>
  <div class="field">
    <%= f.label :netblock %><br>
    <%= f.text_field :netblock %>
  </div>
  <div class="field">
    <%= f.label :subnet %><br>
    <%= f.text_field :subnet %>
  </div>
  <div class="field">
    <%= f.label :network_id %><br>
    <%= f.text_field :network_id %>
  </div>
  <div class="field">
    <%= f.label :reputation %><br>
    <%= f.number_field :reputation %>
  </div>
  <div class="field">
    <%= f.label :dns_id %><br>
    <%= f.text_field :dns_id %>
  </div>
  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.text_field :organization_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Battlefield/Dashboards/BloatedInternalDash/app/views/ips/edit.html.erb
<h1>Editing Ip</h1>

<%= render 'form' %>

<%= link_to 'Show', @ip %> |
<%= link_to 'Back', ips_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/ips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ips</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Hostname</th>
      <th>Dns</th>
      <th>Isp</th>
      <th>Netblock</th>
      <th>Subnet</th>
      <th>Network</th>
      <th>Reputation</th>
      <th>Dns</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ips.each do |ip| %>
      <tr>
        <td><%= ip.address %></td>
        <td><%= ip.hostname %></td>
        <td><%= ip.dns %></td>
        <td><%= ip.isp %></td>
        <td><%= ip.netblock %></td>
        <td><%= ip.subnet %></td>
        <td><%= ip.network %></td>
        <td><%= ip.reputation %></td>
        <td><%= ip.dns %></td>
        <td><%= ip.organization %></td>
        <td><%= link_to 'Show', ip %></td>
        <td><%= link_to 'Edit', edit_ip_path(ip) %></td>
        <td><%= link_to 'Destroy', ip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ip', new_ip_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/ips/new.html.erb
<h1>New Ip</h1>

<%= render 'form' %>

<%= link_to 'Back', ips_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/ips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @ip.address %>
</p>

<p>
  <strong>Hostname:</strong>
  <%= @ip.hostname %>
</p>

<p>
  <strong>Dns:</strong>
  <%= @ip.dns %>
</p>

<p>
  <strong>Isp:</strong>
  <%= @ip.isp %>
</p>

<p>
  <strong>Netblock:</strong>
  <%= @ip.netblock %>
</p>

<p>
  <strong>Subnet:</strong>
  <%= @ip.subnet %>
</p>

<p>
  <strong>Network:</strong>
  <%= @ip.network %>
</p>

<p>
  <strong>Reputation:</strong>
  <%= @ip.reputation %>
</p>

<p>
  <strong>Dns:</strong>
  <%= @ip.dns %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @ip.organization %>
</p>

<%= link_to 'Edit', edit_ip_path(@ip) %> |
<%= link_to 'Back', ips_path %>