Battlefield/Dashboards/BloatedInternalDash/config/routes.rb
Rails.application.routes.draw do

  resources :systems

  namespace :api do
    resources :projects do
      resources :issues #, only: [:create, :update, :destroy]
    end

    resources :servers do
      resources :services
      resources :connections
      resources :pids
    end

  end

  get 'progress/main'

  get 'progress/detail'

  get 'progress/graphs'

  get 'progress/statistics'

  get 'files/index'

  get 'files/download'

  get 'files/upload'

  get 'public/index'

  get 'public/show'

   resources :projects do
     resources :issuelists
     resources :tasklists
   end
  resources :notifications
  resources :networks
  resources :network_boxes
  resources :memberships
  resources :logfiles
  resources :logentries
  resources :hardwares
  resources :githubs
  resources :gists
  resources :groups
  resources :domainnames
  resources :networks
  resources :clusters
  resources :services
  resources :infrastructures
  resources :organizations
  resources :labels
  resources :milestones
  resources :todos

  resources :tasklists do
    resources :tasks
  end
  resources :issuelists do
    resources :issues
  end

  resources :ips
  get 'home/slice'

  resources :ips
  resources :reputations
  resources :ips
  resources :organizations
  resources :nodes
  resources :servers
  get 'dashboard/index'

  get 'dashboard/controls'

  get 'dashboard/analysis'

  devise_for :users
  get 'clusterjobs/new'

  get 'clusterjobs/index'

  get 'main/index'

  root 'main#index'

  resources :systems
  get 'progress/main'

  get 'progress/detail'

  get 'progress/graphs'

  get 'progress/statistics'

  get 'files/index'

  get 'files/download'

  get 'files/upload'

  get 'public/index'

  get 'public/show'

  resources :notifications
  resources :networks
  resources :network_boxes
  resources :memberships
  resources :logfiles
  resources :logentries
  resources :hardwares
  resources :githubs
  resources :gists
  resources :groups
  resources :domainnames
  resources :networks
  resources :clusters
  resources :services
  resources :infrastructures
  resources :organizations
  resources :labels
  resources :milestones
  resources :todos
  resources :tasks
  resources :tasklists
  resources :issues
  resources :issuelists
  resources :projects
  resources :ips
  get 'home/slice'

end

Battlefield/Dashboards/BloatedInternalDash/app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :server
  belongs_to :webserver
  belongs_to :machine
  belongs_to :cluster
  belongs_to :user
  belongs_to :network
  belongs_to :manager
  belongs_to :devops
end

Battlefield/Dashboards/BloatedInternalDash/app/models/supermodels/serv/service.rb
module Serv
class Service <  ActiveRecord::Base

	belongs_to :machine
	belongs_to :server
	belongs_to :node
belongs_to :user
belongs_to :cluster
has_many :statistics
	has_many :configurations
has_many :applications
has_many :processes
has_many :connections
has_many :harddisks
has_many :logfiles
belongs_to  :manager
belongs_to :network
belongs_to :infrastructure
has_many :messages
has_many :notifications

	end
end

Battlefield/Dashboards/BloatedInternalDash/app/models/supermodels/service.rb
  class Service <  ActiveRecord::Base
  # include Mongoid::Document
  # field :name, type: String
  # field :description, type: String
  # field :type, type: String
  # field :location, type: String
  # field :server_id, type: Integer
  # field :webserver_id, type: Integer
  # field :cluster_id, type: Integer
  # field :user_id, type: Integer
  # field :distribution, type: String
  # field :cluster, type: String
  # field :replication, type: String
  # field :authority, type: String
  # field :purpose, type: String
  # field :watchdog, type: String
  # field :pid, type: Integer
  # field :criticality, type: Integer
  # field :priority, type: Integer
  # field :network_id, type: Integer
  # field :manager_id, type: Integer
  # field :devops_id, type: Integer
  # field :configuration, type: String



  belongs_to :machine
  belongs_to :server
  belongs_to :node
belongs_to :user
belongs_to :cluster
has_many :statistics
  has_many :configurations
has_many :applications
has_many :processes
has_many :connections
has_many :harddisks
has_many :logfiles
belongs_to  :manager
belongs_to :network
belongs_to :infrastructure
has_many :messages
has_many :notifications

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}"])
    else
      self.all
    end
  end

end

Battlefield/Dashboards/BloatedInternalDash/app/controllers/api/services_controller.rb
class Api::ServicesController < Api::ApiController
  before_filter :find_server

  def create
    service = @server.services.new(service_params)
    if service.save
      render status: 200, json: {
                            message: "Successfully created Service.",
                            server: @server,
                            service: service
                        }.to_json
    else
      render status: 422, json: {
                            message: "Service creation failed.",
                            errors: service.errors
                        }.to_json
    end
  end


  def update
    service = @server.services.find(params[:id])
    if service.update(service_params)
      render status: 200, json: {
                            message: "Successfully updated Service.",
                            server: @server,
                            service: service
                        }.to_json
    else
      render status: 422, json: {
                            message: "Service update failed.",
                            errors: service.errors
                        }.to_json
    end
  end

  def destroy
    service = @server.services.find(params[:id])
    service.destroy
    render status: 200, json: {
                          message: "Service successfully deleted.",
                          server: @server,
                          service: service
                      }.to_json
  end

  private

  def find_server
    @server = current_user.servers.find(params[:server_id])
  end

  def set_service
    @service = Service.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:name, :description, :type, :location, :webserver_id, :distribution, :cluster, :replication, :authority, :purpose, :watchdog, :pid, :criticality, :priority, :configuration)
  end
end

Battlefield/Dashboards/BloatedInternalDash/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :type, :location, :server_id, :webserver_id, :machine_id, :cluster_id, :user_id, :distribution, :cluster, :replication, :authority, :purpose, :watchdog, :pid, :criticality, :priority, :network_id, :manager_id, :devops_id, :configuration)
    end
end

Battlefield/Dashboards/BloatedInternalDash/app/helpers/services_helper.rb
module ServicesHelper
end

Battlefield/Dashboards/BloatedInternalDash/app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :server_id %><br>
    <%= f.text_field :server_id %>
  </div>
  <div class="field">
    <%= f.label :webserver_id %><br>
    <%= f.text_field :webserver_id %>
  </div>
  <div class="field">
    <%= f.label :machine_id %><br>
    <%= f.text_field :machine_id %>
  </div>
  <div class="field">
    <%= f.label :cluster_id %><br>
    <%= f.text_field :cluster_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :distribution %><br>
    <%= f.text_field :distribution %>
  </div>
  <div class="field">
    <%= f.label :cluster %><br>
    <%= f.text_field :cluster %>
  </div>
  <div class="field">
    <%= f.label :replication %><br>
    <%= f.text_field :replication %>
  </div>
  <div class="field">
    <%= f.label :authority %><br>
    <%= f.text_field :authority %>
  </div>
  <div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>
  <div class="field">
    <%= f.label :watchdog %><br>
    <%= f.text_field :watchdog %>
  </div>
  <div class="field">
    <%= f.label :pid %><br>
    <%= f.number_field :pid %>
  </div>
  <div class="field">
    <%= f.label :criticality %><br>
    <%= f.number_field :criticality %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :network_id %><br>
    <%= f.text_field :network_id %>
  </div>
  <div class="field">
    <%= f.label :manager_id %><br>
    <%= f.text_field :manager_id %>
  </div>
  <div class="field">
    <%= f.label :devops_id %><br>
    <%= f.text_field :devops_id %>
  </div>
  <div class="field">
    <%= f.label :configuration %><br>
    <%= f.text_area :configuration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Battlefield/Dashboards/BloatedInternalDash/app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th>Location</th>
      <th>Server</th>
      <th>Webserver</th>
      <th>Machine</th>
      <th>Cluster</th>
      <th>User</th>
      <th>Distribution</th>
      <th>Cluster</th>
      <th>Replication</th>
      <th>Authority</th>
      <th>Purpose</th>
      <th>Watchdog</th>
      <th>Pid</th>
      <th>Criticality</th>
      <th>Priority</th>
      <th>Network</th>
      <th>Manager</th>
      <th>Devops</th>
      <th>Configuration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.type %></td>
        <td><%= service.location %></td>
        <td><%= service.server %></td>
        <td><%= service.webserver %></td>
        <td><%= service.machine %></td>
        <td><%= service.cluster %></td>
        <td><%= service.user %></td>
        <td><%= service.distribution %></td>
        <td><%= service.cluster %></td>
        <td><%= service.replication %></td>
        <td><%= service.authority %></td>
        <td><%= service.purpose %></td>
        <td><%= service.watchdog %></td>
        <td><%= service.pid %></td>
        <td><%= service.criticality %></td>
        <td><%= service.priority %></td>
        <td><%= service.network %></td>
        <td><%= service.manager %></td>
        <td><%= service.devops %></td>
        <td><%= service.configuration %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @service.type %>
</p>

<p>
  <strong>Location:</strong>
  <%= @service.location %>
</p>

<p>
  <strong>Server:</strong>
  <%= @service.server %>
</p>

<p>
  <strong>Webserver:</strong>
  <%= @service.webserver %>
</p>

<p>
  <strong>Machine:</strong>
  <%= @service.machine %>
</p>

<p>
  <strong>Cluster:</strong>
  <%= @service.cluster %>
</p>

<p>
  <strong>User:</strong>
  <%= @service.user %>
</p>

<p>
  <strong>Distribution:</strong>
  <%= @service.distribution %>
</p>

<p>
  <strong>Cluster:</strong>
  <%= @service.cluster %>
</p>

<p>
  <strong>Replication:</strong>
  <%= @service.replication %>
</p>

<p>
  <strong>Authority:</strong>
  <%= @service.authority %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @service.purpose %>
</p>

<p>
  <strong>Watchdog:</strong>
  <%= @service.watchdog %>
</p>

<p>
  <strong>Pid:</strong>
  <%= @service.pid %>
</p>

<p>
  <strong>Criticality:</strong>
  <%= @service.criticality %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @service.priority %>
</p>

<p>
  <strong>Network:</strong>
  <%= @service.network %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @service.manager %>
</p>

<p>
  <strong>Devops:</strong>
  <%= @service.devops %>
</p>

<p>
  <strong>Configuration:</strong>
  <%= @service.configuration %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>