Battlefield/Dashboards/BloatedInternalDash/config/routes.rb
Rails.application.routes.draw do

  resources :systems

  namespace :api do
    resources :projects do
      resources :issues #, only: [:create, :update, :destroy]
    end

    resources :servers do
      resources :services
      resources :connections
      resources :pids
    end

  end

  get 'progress/main'

  get 'progress/detail'

  get 'progress/graphs'

  get 'progress/statistics'

  get 'files/index'

  get 'files/download'

  get 'files/upload'

  get 'public/index'

  get 'public/show'

   resources :projects do
     resources :issuelists
     resources :tasklists
   end
  resources :notifications
  resources :networks
  resources :network_boxes
  resources :memberships
  resources :logfiles
  resources :logentries
  resources :hardwares
  resources :githubs
  resources :gists
  resources :groups
  resources :domainnames
  resources :networks
  resources :clusters
  resources :services
  resources :infrastructures
  resources :organizations
  resources :labels
  resources :milestones
  resources :todos

  resources :tasklists do
    resources :tasks
  end
  resources :issuelists do
    resources :issues
  end

  resources :ips
  get 'home/slice'

  resources :ips
  resources :reputations
  resources :ips
  resources :organizations
  resources :nodes
  resources :servers
  get 'dashboard/index'

  get 'dashboard/controls'

  get 'dashboard/analysis'

  devise_for :users
  get 'clusterjobs/new'

  get 'clusterjobs/index'

  get 'main/index'

  root 'main#index'

  resources :systems
  get 'progress/main'

  get 'progress/detail'

  get 'progress/graphs'

  get 'progress/statistics'

  get 'files/index'

  get 'files/download'

  get 'files/upload'

  get 'public/index'

  get 'public/show'

  resources :notifications
  resources :networks
  resources :network_boxes
  resources :memberships
  resources :logfiles
  resources :logentries
  resources :hardwares
  resources :githubs
  resources :gists
  resources :groups
  resources :domainnames
  resources :networks
  resources :clusters
  resources :services
  resources :infrastructures
  resources :organizations
  resources :labels
  resources :milestones
  resources :todos
  resources :tasks
  resources :tasklists
  resources :issues
  resources :issuelists
  resources :projects
  resources :ips
  get 'home/slice'

end

Battlefield/Dashboards/BloatedInternalDash/app/models/supermodels/proj/tasklist.rb
class Tasklist < ActiveRecord::Base
	 has_many :tasks
	belongs_to :project

end

Battlefield/Dashboards/BloatedInternalDash/app/models/tasklist.rb
class Tasklist < ActiveRecord::Base
  belongs_to :project
end

Battlefield/Dashboards/BloatedInternalDash/app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  before_action :set_tasklist, only: [:show, :edit, :update, :destroy]

  # GET /tasklists
  # GET /tasklists.json
  def index
    @tasklists = Tasklist.all
  end

  # GET /tasklists/1
  # GET /tasklists/1.json
  def show
  end

  # GET /tasklists/new
  def new
    @tasklist = Tasklist.new
  end

  # GET /tasklists/1/edit
  def edit
  end

  # POST /tasklists
  # POST /tasklists.json
  def create
    @tasklist = Tasklist.new(tasklist_params)

    respond_to do |format|
      if @tasklist.save
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully created.' }
        format.json { render :show, status: :created, location: @tasklist }
      else
        format.html { render :new }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasklists/1
  # PATCH/PUT /tasklists/1.json
  def update
    respond_to do |format|
      if @tasklist.update(tasklist_params)
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully updated.' }
        format.json { render :show, status: :ok, location: @tasklist }
      else
        format.html { render :edit }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasklists/1
  # DELETE /tasklists/1.json
  def destroy
    @tasklist.destroy
    respond_to do |format|
      format.html { redirect_to tasklists_url, notice: 'Tasklist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tasklist
      @tasklist = Tasklist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tasklist_params
      params.require(:tasklist).permit(:name, :desc, :total_tasks, :project_id)
    end
end

Battlefield/Dashboards/BloatedInternalDash/app/helpers/tasklists_helper.rb
module TasklistsHelper
end

Battlefield/Dashboards/BloatedInternalDash/app/views/tasklists/_form.html.erb
<%= form_for(@tasklist) do |f| %>
  <% if @tasklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tasklist.errors.count, "error") %> prohibited this tasklist from being saved:</h2>

      <ul>
      <% @tasklist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :total_tasks %><br>
    <%= f.number_field :total_tasks %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Battlefield/Dashboards/BloatedInternalDash/app/views/tasklists/edit.html.erb
<h1>Editing Tasklist</h1>

<%= render 'form' %>

<%= link_to 'Show', @tasklist %> |
<%= link_to 'Back', tasklists_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/tasklists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasklists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Total tasks</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasklists.each do |tasklist| %>
      <tr>
        <td><%= tasklist.name %></td>
        <td><%= tasklist.desc %></td>
        <td><%= tasklist.total_tasks %></td>
        <td><%= tasklist.project %></td>
        <td><%= link_to 'Show', tasklist %></td>
        <td><%= link_to 'Edit', edit_tasklist_path(tasklist) %></td>
        <td><%= link_to 'Destroy', tasklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tasklist', new_tasklist_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/tasklists/new.html.erb
<h1>New Tasklist</h1>

<%= render 'form' %>

<%= link_to 'Back', tasklists_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/tasklists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tasklist.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @tasklist.desc %>
</p>

<p>
  <strong>Total tasks:</strong>
  <%= @tasklist.total_tasks %>
</p>

<p>
  <strong>Project:</strong>
  <%= @tasklist.project %>
</p>

<%= link_to 'Edit', edit_tasklist_path(@tasklist) %> |
<%= link_to 'Back', tasklists_path %>