Battlefield/Dashboards/BloatedInternalDash/config/routes.rb
Rails.application.routes.draw do

  resources :systems

  namespace :api do
    resources :projects do
      resources :issues #, only: [:create, :update, :destroy]
    end

    resources :servers do
      resources :services
      resources :connections
      resources :pids
    end

  end

  get 'progress/main'

  get 'progress/detail'

  get 'progress/graphs'

  get 'progress/statistics'

  get 'files/index'

  get 'files/download'

  get 'files/upload'

  get 'public/index'

  get 'public/show'

   resources :projects do
     resources :issuelists
     resources :tasklists
   end
  resources :notifications
  resources :networks
  resources :network_boxes
  resources :memberships
  resources :logfiles
  resources :logentries
  resources :hardwares
  resources :githubs
  resources :gists
  resources :groups
  resources :domainnames
  resources :networks
  resources :clusters
  resources :services
  resources :infrastructures
  resources :organizations
  resources :labels
  resources :milestones
  resources :todos

  resources :tasklists do
    resources :tasks
  end
  resources :issuelists do
    resources :issues
  end

  resources :ips
  get 'home/slice'

  resources :ips
  resources :reputations
  resources :ips
  resources :organizations
  resources :nodes
  resources :servers
  get 'dashboard/index'

  get 'dashboard/controls'

  get 'dashboard/analysis'

  devise_for :users
  get 'clusterjobs/new'

  get 'clusterjobs/index'

  get 'main/index'

  root 'main#index'

  resources :systems
  get 'progress/main'

  get 'progress/detail'

  get 'progress/graphs'

  get 'progress/statistics'

  get 'files/index'

  get 'files/download'

  get 'files/upload'

  get 'public/index'

  get 'public/show'

  resources :notifications
  resources :networks
  resources :network_boxes
  resources :memberships
  resources :logfiles
  resources :logentries
  resources :hardwares
  resources :githubs
  resources :gists
  resources :groups
  resources :domainnames
  resources :networks
  resources :clusters
  resources :services
  resources :infrastructures
  resources :organizations
  resources :labels
  resources :milestones
  resources :todos
  resources :tasks
  resources :tasklists
  resources :issues
  resources :issuelists
  resources :projects
  resources :ips
  get 'home/slice'

end

Battlefield/Dashboards/BloatedInternalDash/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :infrastructure
  belongs_to :research
  belongs_to :developer
  belongs_to :application
  belongs_to :username
  belongs_to :user
  #belongs_to :member
  belongs_to :organization

  has_many :issuelists
  has_many :tasklists
  has_many :issues
  has_many :tasks
  has_many :bugs
  has_many :todos

  accepts_nested_attributes_for :tasks
  accepts_nested_attributes_for :issues
  accepts_nested_attributes_for :issuelists
  accepts_nested_attributes_for :tasklists, allow_destroy: true
end

Battlefield/Dashboards/BloatedInternalDash/app/models/supermodels/proj/project.rb
class Project  < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_and_belongs_to_many :developers
	has_and_belongs_to_many :researchers
	has_and_belongs_to_many :applications

	belongs_to :infrastructure
end

Battlefield/Dashboards/BloatedInternalDash/app/controllers/api/projects_controller.rb
class API::ProjectsController <  Api::ApiController


  def index
    Rails.logger.info "Current user: #{current_user.inspect}"
    render json: Node.all
  end

  def show
    node = current_user.nodes.find(params[:id])
    render json: node.as_json(include:[:nodes])
  end

  def create
    node = current_user.nodes.new(node_params)
    if node.save
      render status: 200, json: {
                            message: "Successfully created Node.",
                            node: node
                        }.to_json
    else
      render status: 422, json: {
                            errors: node.errors
                        }.to_json
    end
  end

  def update
    node = current_user.nodes.find(params[:id])
    if node.update(node_params)
      render status: 200, json: {
                            message: "Successfully updated",
                            node: node
                        }.to_json
    else
      render status: 422, json: {
                            errors: node.errors
                        }.to_json
    end
  end

  def destroy
    node = current_user.nodes.find(params[:id])
    node.destroy
    render status: 200, json: {
                          message: "Successfully deleted node."
                      }.to_json
  end

  private
  def node_params
    params.require("node").permit("title")
  end


  def search
    @q = Person.ransack(params[:q])
    @projects = @q.results.includes(:issues, :tasks).page(params[:page]).to_a.uniq
  end
end

Battlefield/Dashboards/BloatedInternalDash/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    #@projects = Project.all
    @q = Project.ransack(params[:q])
    @projects = @q.result.includes(:issues, :tasks).page(params[:page]).to_a.uniq

  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    #@issues = @project.issues
    @q = @project.issues.ransack(params[:q])
    @issues = @q.result.page(params[:page])

    @issueslists = @project.issuelists
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :details, :infrastructure_id, :research_id, :developer_id, :application_id, :projected_completion, :username_id, :user_id, :member_id, :manhours, :eta, :completion_percentage, :_destroy)
    end
end

Battlefield/Dashboards/BloatedInternalDash/app/helpers/projects_helper.rb
module ProjectsHelper
end

Battlefield/Dashboards/BloatedInternalDash/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :projected_completion %><br>
    <%= f.datetime_select :projected_completion %>
  </div>
  <div class="field">
    <%= f.label :manhours %><br>
    <%= f.number_field :manhours %>
  </div>
  <div class="field">
    <%= f.label :eta %><br>
    <%= f.number_field :eta %>
  </div>
  <div class="field">
    <%= f.label :completion_percentage %><br>
    <%= f.text_field :completion_percentage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Battlefield/Dashboards/BloatedInternalDash/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<%= search_form_for @q do |f| %>
  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>

  <%= f.label :description_cont %>
  <%= f.search_field :description_cont %>

  <%= f.submit %>
  <% end %>


<table>
  <thead>
    <tr>
      <th><%= sort_link(@q, :name) %></th>
      <th>Description</th>
      <th>Details</th>
      <th>Infrastructure</th>
      <th>Research</th>
      <th>Developer</th>
      <th>Application</th>
      <th>Projected completion</th>
      <th>Username</th>

      <th>Member</th>
      <th>Manhours</th>
      <th>Eta</th>
      <th>Completion percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.details %></td>
        <td><%= project.projected_completion %></td>
        <td><%= project.manhours %></td>
        <td><%= project.eta %></td>
        <td><%= project.completion_percentage %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

Battlefield/Dashboards/BloatedInternalDash/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong></strong>
  <%= @project.name %></h1>
<h3> <%= @project.description %> - <%= @project.completion_percentage %>% Complete</h3>

<p>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
</p>

<div id="detailsbox">
<p>
  <strong>Details:</strong>
  <%= @project.details %>
</p>
</div>

<p>
  <strong>Projected completion:</strong>
  <%= @project.projected_completion %>
</p>


<p>
  <strong>Manhours:</strong>
  <%= @project.manhours %>
</p>

<p>
  <strong>Eta:</strong>
  <%= @project.eta %>
</p>



<h3>Project Issues</h3>

<p><h4>Search Issues</h4>
<%= search_form_for @q do |f| %>
  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>

  <%= f.submit %>
<% end %>

</p>


<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Author</th>
    <th>Assignee</th>

    <th>Label</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @issues.each do |issue| %>
    <tr>
      <td><%= issue.name %></td>
      <td><%= issue.author %></td>
      <td><%= issue.assignee %></td>
      <td><%= issue.label %></td>
      <td><%= link_to 'Show', issue %></td>
      <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
      <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>